title: BHN Data Team Wiki
description: Documentation for reporting systems, team workflows, and program logic.
baseurl: "/BHN-Data-Team-Wiki"  # Base URL for GitHub Pages
permalink: /docs/:path/
theme: jekyll-theme-git-wiki
markdown: kramdown
highlighter: rouge

# Optional but useful for sidebar and navigation
collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: default

# Plugins (optional; depends on GitHub Pages support)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - node_modules/
  - Gemfile
